### ISSUE TITLE
Input files are opened with O_NOFOLLOW

### ISSUE THREAD

**Issue by atsampson** [aperezdc/signify#8]
I'm using signify to verify distfile signatures in a ports system. When building a port that I've previously downloaded distfiles for, the system makes symlinks into the distfile cache rather than downloading the distfiles again.

This breaks signify, because `readb64file` and `readmsg` both open files with `O_NOFOLLOW`:

```
signify: can't open SHA256.sig for reading: Too many levels of symbolic links
```

Is this intentional? (Wanting to verify a signed file that is itself a symlink seems legitimate...)

**Comment by aperezdc** [comment]
@atsampson: I cannot give you a 100% accurate answer, but it seems to be intentional, because I am just importing the code from upstream with the minimum amount of changes needed to make `signify` build in non-BSD systems.

My understanding is that one wants to check signatures of the actual files, without following links, to avoid situations like a script calling `signify` and then a different program uses file after the symlink has been tampered with during the small window between the invocation of both programs. For example:

1. The signature of a file is checked, through a symlink, with the intention of installing a software package. The symlink points to a legit package, and the verification succeeds.
2. A malicious user makes the symlink point to a different location, containing e.g. a rootkit.
3. The software package installs the package through the symlink, and unadvertedly installs the unverified software package.

[Here](https://www.securecoding.cert.org/confluence/display/c/POS01-C.+Check+for+the+existence+of+links+when+dealing+with+files) you can find a longer discussion about why checking for symlinks when opening files is a good idea, and how to do it.

I suppose you could use hard links instead of symbolic links... or somehow resolve symlinks first to their full paths, _then_ verify and use the files via the resolved full path. You might want to validate the full path as well, to ensure that the resolved paths point to valid directories (dunno about how your system works, so I am just throwing suggestions which came to mind :wink: )

**Comment by atsampson** [comment]
Cheers -- if it's from upstream then I'll assume it's intentional and find a workaround. (Although, thinking about it, maybe it should apply the same logic to the files it's verifying with `-C`, not just the signature file... `HASHFileChunk` only uses `O_RDONLY`.)

**Comment by eli-schwartz** [comment]
Yes, trying to prevent malicious writes by checking symlinks doesn't seem very logical. If your file that you're reading is symlinked to a path controlled by other users, I'd say that is a pretty deliberate choice which should be respected anyway.

And it doesn't come with overprotective checks loudly aborting if you try to verify a *non* symlink file which is writable by other users, does it?

Wherever O_NOFOLLOW comes from, it should be fixed. :p So probably speak to the BSD people.
